config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :working_hours do
  member do
    put 'update_comments'
  end
  collection do
    get 'startstop'
    post 'break'
    get 'project_issues'
    match 'vacation/new' => 'working_hours#new_vacation', :via => :get, :as => 'new_vacation'
    match 'vacation' => 'working_hours#create_vacation', :via => :post
    get 'statistics'
  end
end

resources :holidays
resources :working_hours_snapshots

app/models/holiday.rb
class Holiday < ActiveRecord::Base
  unloadable

  validates_presence_of :day, :hours
  validates :day, :date => true

end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  unloadable

  before_filter :require_login
  before_filter :require_admin, :except => :index

  def index
    @holidays = Holiday.order("day DESC")

    # pagination
    @holiday_count = @holidays.count
    @holiday_pages = Paginator.new(@holiday_count, per_page_option, params['page'])
    @holidays = @holidays.limit(@holiday_pages.per_page).offset(@holiday_pages.offset)
  end

  def new
    @holiday = Holiday.new(:day => Date.today, :hours => WorkingHours.workday_hours)
  end

  def create
    @holiday = Holiday.new(params[:holiday])
    if @holiday.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'index'
    else
      render :action => 'new'
    end
  end

  def edit
    @holiday = Holiday.find(params[:id])
  end

  def update
    @holiday = Holiday.find(params[:id])
    @holiday.attributes = params[:holiday]
    if @holiday.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => 'index'
    else
      render :action => 'edit'
    end
  end

  def destroy
    Holiday.find(params[:id]).destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to :action => 'index'
  end

end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= error_messages_for 'holiday' %>

<div class="box tabular">
  <p><%= f.text_field :day, :size => 10, :value => (@holiday.day.to_date.strftime("%Y-%m-%d") rescue nil) %><%= calendar_for('holiday_day') %></p>
  <p><%= f.text_field :hours, :size => 5 %></p>
</div>

app/views/holidays/edit.html.erb
<h2><%= l(:label_holidays) %></h2>

<%= labelled_form_for @holiday, :url => holiday_path(@holiday) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

<p><%= link_to l(:button_back), holidays_path %></p>

app/views/holidays/index.html.erb
<% if User.current.admin? %>
  <div class="contextual">
    <%= link_to l(:button_add), new_holiday_path, :class => 'icon icon-add' %>
  </div>
<% end %>

<h2><%= l(:label_holidays) %></h2>

<% if @holidays.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_day) %></th>
        <th><%= l(:field_hours) %></th>
        <% if User.current.admin? %>
          <th></th>
          <th></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
    <% @holidays.each do |entry| %>
      <tr>
        <td><%= entry.day %></td>
        <td><%= entry.hours %>h</td>
        <% if User.current.admin? %>
          <td><%= link_to l(:button_edit), edit_holiday_path(entry), :class => 'icon icon-edit' %></td>
          <td><%= link_to l(:button_delete), holiday_path(entry), :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon icon-del' %></td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<p class="pagination"><%= pagination_links_full @holiday_pages, @holiday_count %></p>

app/views/holidays/new.html.erb
<h2><%= l(:label_holidays_new) %></h2>

<%= labelled_form_for @holiday, :url => holidays_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
<% end %>

<p><%= link_to l(:button_back), holidays_path %></p>