config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :working_hours do
  member do
    put 'update_comments'
  end
  collection do
    get 'startstop'
    post 'break'
    get 'project_issues'
    match 'vacation/new' => 'working_hours#new_vacation', :via => :get, :as => 'new_vacation'
    match 'vacation' => 'working_hours#create_vacation', :via => :post
    get 'statistics'
  end
end

resources :holidays
resources :working_hours_snapshots

app/models/working_hours_snapshot.rb
class WorkingHoursSnapshot < ActiveRecord::Base
  unloadable

  belongs_to :user

  validates_presence_of :user, :date
  validates :date, :date => true

  def self.find_current(user, start_date, end_date)
    where(:user_id => user.id).where("date >= ? AND date <= ?", start_date, end_date).order("date DESC").first
  end

end

app/controllers/working_hours_snapshots_controller.rb
class WorkingHoursSnapshotsController < ApplicationController
  unloadable

  before_filter :require_admin

  def index
    @snapshots = WorkingHoursSnapshot.order("date DESC")

    # pagination
    @snapshot_count = @snapshots.count
    @snapshot_pages = Paginator.new(@snapshot_count, per_page_option, params['page'])
    @snapshots = @snapshots.limit(@snapshot_pages.per_page).offset(@snapshot_pages.offset)
  end

  def new
    @snapshot = WorkingHoursSnapshot.new(:user_id => User.current.id, :date => Date.today, :total => 0, :target => 0, :vacation_days => 0)
    @users = User.sorted
  end

  def create
    @snapshot = WorkingHoursSnapshot.new(params[:working_hours_snapshot])
    if @snapshot.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'index'
    else
      @users = User.sorted
      render :action => 'new'
    end
  end

  def edit
    @snapshot = WorkingHoursSnapshot.find(params[:id])
    @users = User.sorted
  end

  def update
    @snapshot = WorkingHoursSnapshot.find(params[:id])
    @snapshot.attributes = params[:working_hours_snapshot]
    if @snapshot.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => 'index'
    else
      @users = User.sorted
      render :action => 'edit'
    end
  end

  def destroy
    WorkingHoursSnapshot.find(params[:id]).destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to :action => 'index'
  end

end

app/helpers/working_hours_snapshots_helper.rb
module WorkingHoursSnapshotsHelper
end

app/views/working_hours_snapshots/_form.html.erb
<%= error_messages_for 'snapshot' %>

<div class="box tabular">
  <p>
    <%= label_tag 'working_hours_snapshot_user_id', l(:field_user) %>
    <%= f.collection_select :user_id, @users, :id, :name, {:include_blank => false} %>
  </p>
  <p><%= f.text_field :date, :size => 10, :value => (@snapshot.date.to_date.strftime("%Y-%m-%d") rescue nil) %><%= calendar_for('working_hours_snapshot_date') %></p>
  <p><%= f.text_field :total, :size => 5 %> min</p>
  <p><%= f.text_field :target, :size => 5 %> min</p>
  <p><%= f.text_field :vacation_days, :size => 5 %> d</p>
</div>

app/views/working_hours_snapshots/edit.html.erb
<h2><%= l(:label_working_hours_snapshot_edit) %></h2>

<%= labelled_form_for @snapshot, :url => working_hours_snapshot_path(@snapshot) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

<p><%= link_to l(:button_back), working_hours_snapshots_path %></p>

app/views/working_hours_snapshots/index.html.erb
<div class="contextual">
  <%= link_to l(:button_add), new_working_hours_snapshot_path, :class => 'icon icon-add' %>
</div>

<h2><%= l(:label_working_hours_snapshots) %></h2>

<% if @snapshots.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <table class="list">
    <thead>
      <tr>
        <th><%= l(:field_user) %></th>
        <th><%= l(:field_date) %></th>
        <th><%= l(:field_total) %></th>
        <th><%= l(:field_target) %></th>
        <th><%= l(:field_vacation_days) %></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
    <% @snapshots.each do |entry| %>
      <tr>
        <td><%= User.find(entry.user_id).name %></td>
        <td><%= entry.date %></td>
        <td><%= entry.total %>' (<%= "#{'%.1f' % (entry.total/60.0)}h" %>)</td>
        <td><%= entry.target %>' (<%= "#{'%.1f' % (entry.target/60.0)}h" %>)</td>
        <td><%= entry.vacation_days %> d</td>
        <td><%= link_to l(:button_edit), edit_working_hours_snapshot_path(entry), :class => 'icon icon-edit' %></td>
        <td><%= link_to l(:button_delete), working_hours_snapshot_path(entry), :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon icon-del' %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

<p class="pagination"><%= pagination_links_full @snapshot_pages, @snapshot_count %></p>

app/views/working_hours_snapshots/new.html.erb
<h2><%= l(:label_working_hours_snapshots_new) %></h2>

<%= labelled_form_for @snapshot, :url => working_hours_snapshots_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
<% end %>

<p><%= link_to l(:button_back), working_hours_snapshots_path %></p>