config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :working_hours do
  member do
    put 'update_comments'
  end
  collection do
    get 'startstop'
    post 'break'
    get 'project_issues'
    match 'vacation/new' => 'working_hours#new_vacation', :via => :get, :as => 'new_vacation'
    match 'vacation' => 'working_hours#create_vacation', :via => :post
    get 'statistics'
  end
end

resources :holidays
resources :working_hours_snapshots

app/controllers/working_hours_controller.rb
class WorkingHoursController < ApplicationController
  unloadable

  before_filter :require_login
  accept_api_auth :index

  def index
    # filter
    filter_params = params[:filter] || {}

    if params[:format] == 'ics'
      params[:duration] ||= 365
      @begindate_filter = filter_params[:begindate] || Date.today - params[:duration].to_s.to_i
    else
      @begindate_filter = filter_params[:begindate] || Date.today
    end
    @enddate_filter = filter_params[:enddate] || Date.today

    # apply filter
    @working_hours = WorkingHours
    unless params[:users] == 'all' && User.current.admin?
      @working_hours = @working_hours.where(:user_id => User.current.id)
    end
    @working_hours = @working_hours.where("workday >= ? AND workday <= ?", @begindate_filter, @enddate_filter)
    @working_hours = @working_hours.where(:project_id => filter_params[:project_id]) unless filter_params[:project_id].blank?
    @working_hours = @working_hours.where(:issue_id => filter_params[:issue_id]) unless filter_params[:issue_id].blank?

    respond_to do |format|
      format.html {
        # filter form
        @project_filter_collection = User.current.projects.order(:name)
        @project_filter = filter_params[:project_id].to_s.to_i

        @issue_filter_collection = []
        unless filter_params[:project_id].blank?
          project = User.current.projects.find(filter_params[:project_id])
          @issue_filter_collection = WorkingHours.task_issues(project)
          @issue_filter = filter_params[:issue_id].to_s.to_i
        end

        @minutes_total = @working_hours.inject(0) { |sum, w| sum + w.minutes }

        # pagination
        @working_hour_count = @working_hours.count
        @working_hour_pages = Paginator.new(@working_hour_count, per_page_option, params['page'])
        @working_hours = @working_hours.order("#{WorkingHours.table_name}.starting DESC").limit(@working_hour_pages.per_page).offset(@working_hour_pages.offset)
      }
      format.csv {
        send_csv
      }
      format.ics {
        send_ics
      }
    end
  end

  def new
    @working_hours = WorkingHours.start(User.current, Time.now)
    project = User.current.projects.order(:name).first
    @issues = WorkingHours.task_issues(project)
  end

  def create
    @working_hours = WorkingHours.new(params[:working_hours])
    @working_hours.user = User.current
    working_hours_calculations
    if @working_hours.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to :action => 'index', :filter => params[:filter]
    else
      @issues = WorkingHours.task_issues(@working_hours.project)
      render :action => 'new'
    end
  end

  def new_vacation
    @working_hours = WorkingHours.new
    @vacation_start_date = Date.today
    @vacation_end_date = Date.today

    flash[:error] = l(:error_no_vacation_issue) if WorkingHours.vacation_issue.nil?
  end

  def create_vacation
    vacation_issue = WorkingHours.vacation_issue
    if vacation_issue.nil?
      flash[:error] = l(:error_no_vacation_issue)
      redirect_to :action => 'index', :filter => params[:filter]
      return
    end

    start_date = params[:vacation_start_date].to_date rescue nil
    end_date = params[:vacation_end_date].to_date rescue nil
    if start_date.nil? || end_date.nil? || end_date < start_date
      @working_hours = WorkingHours.new(params[:working_hours])
      @working_hours.errors.add(:starting, :invalid) if start_date.nil?
      @working_hours.errors.add(:ending, :invalid) if end_date.nil? || end_date < start_date
      @vacation_start_date = params[:vacation_start_date]
      @vacation_end_date = params[:vacation_end_date]
      render :action => 'new_vacation'
      return
    end

    vacation_project = vacation_issue.project
    holidays = Holiday.where("day >= ? AND day <= ?", start_date, end_date).pluck(:day)

    t = start_date
    num_days = (end_date - start_date + 1).to_int
    num_days.times do
      if t.wday != 0 and t.wday != 6
        # not a weekend
        working_hours = WorkingHours.new(params[:working_hours])
        working_hours.user = User.current
        working_hours.project = vacation_project
        working_hours.issue = vacation_issue
        working_hours.break = 0
        working_hours.workday = t
        working_hours.starting = t.to_time

        if holidays.include?(t)
          # holiday on working day
          holiday = Holiday.find_by_day(t)
          delta_hours = WorkingHours.workday_hours - holiday.hours
          if delta_hours > 0.0
            working_hours.ending = working_hours.starting + delta_hours.hours
            working_hours.save
          end
        else
          # working day
          working_hours.ending = working_hours.starting + WorkingHours.workday_hours.hours
          working_hours.save
        end
      end
      t += 1
    end

    flash[:notice] = l(:notice_successful_create)
    redirect_to :action => 'index', :filter => params[:filter]
  end

  def edit
    @working_hours = WorkingHours.find(params[:id])
    @issues = WorkingHours.task_issues(@working_hours.project)
  end

  def update
    @working_hours = WorkingHours.find(params[:id])
    @working_hours.attributes = params[:working_hours]
    working_hours_calculations
    if @working_hours.save
      flash[:notice] = l(:notice_successful_update)
      redirect_to :action => 'index', :filter => params[:filter]
    else
      @issues = WorkingHours.task_issues(@working_hours.project)
      render :action => 'edit'
    end
  end

  def destroy
    WorkingHours.find(params[:id]).destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to :action => 'index', :filter => params[:filter]
  end

  def update_comments
    @working_hours = WorkingHours.find(params[:id])
    @working_hours.attributes = params[:working_hours]
    @working_hours.save
    render(:partial => 'my/blocks/working_hours')
  end

  def startstop
    project_id = params[:project_id].to_i
    issue_id = params[:issue_id].to_i
    @cur_entry = startstop_task(User.current, project_id, issue_id)
    render(:partial => 'my/blocks/working_hours')
  end

  def break
    @cur_entry = startstop_task(User.current, nil, nil, true)
    render(:partial => 'my/blocks/working_hours')
  end

  def project_issues
    if params[:project_id].blank?
      @issues = []
    else
      project = User.current.projects.find(params[:project_id])
      @issues = WorkingHours.task_issues(project)
    end
  end

  def statistics
    filter_params = params[:filter] || {}
    @begindate_filter = filter_params[:begindate] || Date.new(Time.now.year, Time.now.month, 1)
    @enddate_filter = filter_params[:enddate] || Date.today - 1.day

    begindate = @begindate_filter.to_date
    enddate = @enddate_filter.to_date
    @actual_hours = WorkingHours.total_minutes(begindate, enddate, User.current) / 60.0
    @target_hours = WorkingHours.target_minutes(begindate, enddate, User.current) / 60.0
    @diff_hours = WorkingHours.diff_minutes(begindate, enddate, User.current) / 60.0
  end

  private

  MINGAP = 60

  def working_hours_calculations
    case params['subform']
      when 'Timestamps'
        if params['running'] && params[:working_hours][:ending].empty?
          @working_hours.ending = nil
        end
        unless @working_hours.starting.blank?
          if @working_hours.starting.hour < WorkingHours::WORKDAY_CHANGE_HOUR
            @working_hours.workday = @working_hours.starting.to_date - 1
          else
            @working_hours.workday = @working_hours.starting.to_date
          end
        end
      when 'Duration'
        unless @working_hours.workday.blank?
          @working_hours.starting = Time.local(@working_hours.workday.year, @working_hours.workday.month, @working_hours.workday.day)
          @working_hours.ending = @working_hours.starting + params['duration'].to_f.hours
        end
    end
  end

  def startstop_task(user, new_project_id, new_issue_id, breakflag=false)
    logger.debug "startstop user #{user.name} task: #{new_project_id} break: #{breakflag}"
    starting = Time.now

    cur = WorkingHours.find_current(user)
    start_task = !(breakflag || new_project_id.nil? || new_project_id == 0)

    # stop current task
    if !cur.nil? && cur.running?
      logger.debug "stop entry #{cur.id} task: #{cur.project_id}"
      if new_project_id == cur.project_id && new_issue_id == cur.issue_id
        # Same task -> stop only
        start_task = false
      end
      cur.ending = starting
      if cur.ending - cur.starting < MINGAP && start_task
        # replace short entry by new one
        starting = cur.starting
        cur.destroy
      else
        cur.save
      end
    elsif start_task
      # check short entries or short gaps
      cur = WorkingHours.where(:user_id => user.id).order("#{WorkingHours.table_name}.starting DESC").first
      unless cur.nil?
        if cur.ending - cur.starting < MINGAP
          # replace short entry by new one
          starting = cur.starting
          cur.destroy
        elsif starting - cur.ending < MINGAP
          # no gap
          starting = cur.ending
        end
        cur = nil
      end
    end

    # start new task
    if start_task
      prev = WorkingHours.where({:user_id => user.id, :project_id => new_project_id}).order("#{WorkingHours.table_name}.starting DESC").first
      cur = WorkingHours.start(user, starting)
      logger.debug "start entry #{cur.id} task: #{cur.project_id}"
      cur.project_id = new_project_id
      cur.issue_id = new_issue_id
      cur.comments = prev.comments if !prev.nil? && starting - prev.ending < 10*3600
      cur.save!
    end

    cur
  rescue Exception => e
    logger.error "Error in startstop user #{user.name} task: #{new_project_id} break: #{breakflag} : #{e.message}"
    nil
  end

  def send_csv
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields

app/helpers/working_hours_helper.rb
module WorkingHoursHelper

  def duration(minutes)
    str = ''
    unless minutes.nil? then
      days = minutes / (24*60)
      hours = (minutes % (24*60)) / 60
      minutes = minutes % 60
      str << days.to_s << "d " if days > 0
      str << hours .to_s << "h " if hours > 0
      str << minutes.to_s << "'" if minutes > 0 || hours+days == 0
    end
    str
  end

  def to_time_s(timestamp, workday)
    include_date = (timestamp.to_date != workday)
    format_time(timestamp, include_date)
  end

end

app/views/working_hours/_form.html.erb
<% content_for :header_tags do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('select#working_hours_project_id').change(function() {
        $.ajax({
          url: "<%= project_issues_working_hours_path %>",
          data: {
            project_id: $(this).val()
          },
          dataType: "script"
        });
      });

      $("input[name='subform']").change(function() {
        var showTimestamps = $(this).val() == 'Timestamps';
        $('#timestamps_subform').toggle(showTimestamps);
        $('#duration_subform').toggle(!showTimestamps);
      });

      $('input#working_hours_ending').bind('change keyup', function() {
        $('input#running').prop('checked', $(this).val().length == 0);
      });

      $('input#running').change(function() {
        if ($(this).is(':checked')) {
          $('input#working_hours_ending').val("");
        }
        else {
          $('input#working_hours_ending').val("<%= @working_hours.ending.nil? ? "" : @working_hours.ending.strftime("%Y-%m-%d %H:%M:%S") %>");
        }
      })
    });
  </script>

  <%= stylesheet_link_tag '/plugin_assets/redmine_working_hours/stylesheets/working_hours' %>
<% end %>

<%= error_messages_for 'working_hours' %>

<% if @working_hours.new_record? && !WorkingHours.vacation_issue.nil? %>
  <div class="tabs">
    <ul>
      <li><%= link_to l(:label_issue), "#", :class => 'selected' %></li>
      <li><%= link_to l(:label_vacation), new_vacation_working_hours_path(:filter => params[:filter]) %></li>
    </ul>
  </div>
<% end %>

<div class="box tabular">
  <p>
    <%= label_tag 'working_hours_project_id', l(:field_project) %>
    <%= f.collection_select :project_id, User.current.projects.order(:name), :id, :name, {:include_blank => false} %>
  </p>
  <p>
    <%= label_tag 'working_hours_issue_id', l(:field_issue) %>
    <%= f.collection_select :issue_id, @issues, :id, :subject, {:include_blank => true} %>
  </p>

  <hr/>

  <%= radio_button_tag 'subform', 'Timestamps', true %> <%= l(:label_timestamps) %>
  <%= radio_button_tag 'subform', 'Duration', false %> <%= l(:label_duration) %>

  <div id="timestamps_subform">
    <p><%= f.text_field :starting, :size => 25, :value => (@working_hours.starting.strftime("%Y-%m-%d %H:%M:%S") rescue nil) %></p>
    <p><%= f.text_field 'break', "size" => 5 %> min</p>
    <p>
      <%= f.text_field :ending, :size => 25, :value => (@working_hours.ending.nil? ? '' : @working_hours.ending.strftime("%Y-%m-%d %H:%M:%S")) %>
      <%= l(:label_running) %><%= check_box_tag 'running', "1", @working_hours.ending.nil? %>
    </p>
  </div>

  <div id="duration_subform" style="display:none">
    <p>
      <%= f.text_field :workday, :size => 10, :value => (@working_hours.workday.strftime("%Y-%m-%d") rescue nil) %>
      <%= calendar_for('working_hours_workday') %>
    </p>
    <p>
      <%= label_tag 'duration', l(:field_hours) %>
      <%= text_field_tag 'duration', ('%.1f' % (@working_hours.minutes/60.0)), "size" => 5 %>
    </p>
  </div>

  <hr/>

  <p><%= f.text_area 'comments', :cols => 40, :rows => 3  %></p>
</div>

app/views/working_hours/_list.html.erb
<table class="list working_hours">
  <thead>
    <tr>
      <th><%= l(:label_project) %></th>
      <th><%= l(:label_issue) %></th>
      <th><%= l(:label_date) %></th>
      <th><%= l(:field_starting) %></th>
      <th><%= l(:field_break) %></th>
      <th><%= l(:field_ending) %></th>
      <th><%= l(:label_comment) %></th>
      <th><%= l(:label_duration) %></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
  <% working_hours.each do |entry| %>
    <tr>
      <td><%= link_to entry.project.name, project_path(entry.project) unless entry.project.nil? %></td>
      <td><%= link_to "##{entry.issue_id} #{truncate(h(entry.issue.subject), :length => 30)}", issue_path(entry.issue) unless entry.issue.nil? %></td>
      <td><%= entry.workday.to_formatted_s(:european) %></td>
      <td><%= to_time_s(entry.starting, entry.workday) unless entry.starting.nil? %></td>
      <td><%= duration(entry.break) %></td>
      <td><%= to_time_s(entry.ending, entry.workday) unless entry.ending.nil? %></td>
      <td title="<%= h(entry.comments) %>"><%= truncate(h(entry.comments), :length => 30) %></td>
      <td><%= duration(entry.minutes) %></td>
      <td><%= link_to l(:button_edit), edit_working_hour_path(entry, :filter => params[:filter]), :class => 'icon icon-edit' %></td>
      <td><%= link_to l(:button_delete), working_hour_path(entry, :filter => params[:filter]), :method => :delete, :confirm => l(:text_are_you_sure), :class => 'icon icon-del' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<p class="pagination"><%= pagination_links_full @working_hour_pages, @working_hour_count %></p>

<%= l(:label_total_time) %>: <%= duration(@minutes_total) %> <%= "(#{'%.1f' % (@minutes_total/60.0)}h)" if @minutes_total >= 60 %>

app/views/working_hours/edit.html.erb
<h2><%= l(:label_working_hours) %></h2>

<%= labelled_form_for @working_hours, :url => working_hour_path(@working_hours, :filter => params[:filter]) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_save) %>
<% end %>

<p><%= link_to l(:button_back), working_hours_path(:filter => params[:filter]) %></p>

app/views/working_hours/index.html.erb
<% content_for :header_tags do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('input#filter_begindate, input#filter_enddate').keyup(function(e) {
        if (e.keyCode == 13) {
          $("#query_form").submit();
        }
      });

      $('select#filter_project_id').change(function() {
        $.ajax({
          url: "<%= project_issues_working_hours_path(:filter => 1) %>",
          data: {
            project_id: $(this).val()
          },
          dataType: "script"
        });
      });

    });
  </script>

  <%= stylesheet_link_tag '/plugin_assets/redmine_working_hours/stylesheets/working_hours' %>
<% end %>

<div class="contextual">
  <%= link_to l(:button_add), new_working_hour_path(:filter => params[:filter]), :class => 'icon icon-add' %>
  <%= link_to l(:label_holidays), holidays_path, :class => 'icon icon-ics' %>
  <% if User.current.admin? %>
    <%= link_to l(:label_working_hours_snapshots), working_hours_snapshots_path, :class => 'icon icon-time' %>
  <% end %>
</div>

<h2><%=l(:label_working_hours)%></h2>

<%= form_tag({ :action => 'index'},:method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible">
        <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
        <div>
          <%= l(:field_starting) %>: <%= text_field_tag 'filter[begindate]', @begindate_filter, :size => 10 %><%= calendar_for('filter_begindate') %>
          <%= l(:field_ending) %>: <%= text_field_tag 'filter[enddate]', @enddate_filter, :size => 10 %><%= calendar_for('filter_enddate') %>
          <%= l(:field_project) %>: <%= collection_select :filter, :project_id, @project_filter_collection, :id, :name, :prompt => l(:label_all), :selected => @project_filter %>
          <%= l(:field_issue) %>: <%= collection_select :filter, :issue_id, @issue_filter_collection, :id, :subject, :prompt => l(:label_all), :selected => @issue_filter %>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
      <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
      <%= link_to l(:button_clear), {}, :class => 'icon icon-reload'  %>
    </p>
  </div>
<% end %>

<% if @working_hours.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
  <%= render :partial => 'working_hours/list', :locals => {:working_hours => @working_hours} %>

  <p class="other-formats">
    <%= l(:label_export_to) %>
    <span><%= link_to 'CSV', params.merge({:format => 'csv'}), :class => 'icon icon-csv' %></span>
    <% if User.current.admin? %>
      <span><%= link_to "CSV (#{l(:field_admin)})", params.merge({:format => 'csv', :users => 'all'}), :class => 'icon icon-csv' %></span>
    <% end %>
    <span><%= link_to 'iCalendar', params.merge({:format => 'ics', :key => User.current.api_key}), :class => 'icon icon-ics' %></span>
  </p>
<% end %>

<h3><%= l(:label_overview) %></h3>

<p><%= l(:label_today_capitalized) %>: <%= duration(WorkingHours.total_minutes_day(Date.today)) %></p>

<%= l(:label_month) %>:
<table class="list">
  <thead>
    <th><%= l(:field_total) %></th>
    <th><%= l(:field_target) %></th>
    <th><%= l(:label_target_remaining) %></th>
    <th><%= l(:label_diff_until_now) %></th>
    <th><%= l(:label_diff_prev_month) %></th>
  </thead>
  <tr>
    <td><%= "#{'%.1f' % (WorkingHours.total_minutes_month(Time.now.month)/60.0)}h" %></td>
    <td><%= "#{'%.1f' % (WorkingHours.target_minutes_month(Time.now.month)/60.0)}h" %></td>
    <td><%= "#{'%.1f' % (-WorkingHours.diff_minutes_until_day(WorkingHours.last_day_of_month(Time.now.month))/60.0)}h" %></td>
    <td><%= "#{'%.1f' % (WorkingHours.diff_minutes_until_day(Date.today - 1.day)/60.0)}h" %></td>
    <td><%= "#{'%.1f' % (WorkingHours.diff_minutes_until_day(Date.new(Time.now.year, Time.now.month, 1) - 1.day)/60.0)}h" %></td>
  </tr>
</table>

<p><%= l(:label_vacation_left) %>: <%= WorkingHours.vacation_days_available %> <%= l(:label_day_plural) %></p>

<p><%= link_to l(:label_working_hours_statistics), statistics_working_hours_path %><p>

app/views/working_hours/new.html.erb
<h2><%= l(:label_working_hours_new) %></h2>

<%= labelled_form_for @working_hours, :url => working_hours_path(:filter => params[:filter]) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
<% end %>

<p><%= link_to l(:button_back), working_hours_path(:filter => params[:filter]) %></p>

app/views/working_hours/new_vacation.html.erb
<h2><%= l(:label_vacation_new) %></h2>

<%= labelled_form_for @working_hours, :url => vacation_working_hours_path(:filter => params[:filter], :vacation => params[:vacation]) do |f| %>
  <%= error_messages_for 'working_hours' %>

  <div class="tabs">
    <ul>
      <li><%= link_to l(:label_issue), new_working_hour_path(:filter => params[:filter]) %></li>
      <li><%= link_to l(:label_vacation), "#", :class => 'selected' %></li>
    </ul>
  </div>

  <div class="box tabular">
    <p>
      <%= label_tag 'vacation_start_date', l(:field_starting) %>
      <%= text_field_tag 'vacation_start_date', @vacation_start_date, :size => 10 %>
      <%= calendar_for('vacation_start_date') %>
    </p>
    <p>
      <%= label_tag 'vacation_end_date', l(:field_ending) %>
      <%= text_field_tag 'vacation_end_date', @vacation_end_date, :size => 10 %>
      <%= calendar_for('vacation_end_date') %>
    </p>

    <hr/>

    <p><%= f.text_area 'comments', :cols => 40, :rows => 3  %></p>
  </div>

  <%= submit_tag l(:button_create) %>
<% end %>

<p><%= link_to l(:button_back), working_hours_path(:filter => params[:filter]) %></p>

app/views/working_hours/project_issues.js.erb
<% if params[:filter] == '1' %><%# update filter form %>
$('select#filter_issue_id').replaceWith("<%= escape_javascript(collection_select :filter, :issue_id, @issues, :id, :subject, :prompt => l(:label_all)) %>");
<% else %><%# update edit form %>
$('select#working_hours_issue_id').replaceWith("<%= escape_javascript(collection_select :working_hours, :issue_id, @issues, :id, :subject, {:include_blank => true}) %>");
<% end %>

app/views/working_hours/statistics.html.erb
<% content_for :header_tags do %>
  <script type="text/javascript">
    $(document).ready(function() {
      $('input#filter_begindate, input#filter_enddate').keyup(function(e) {
        if (e.keyCode == 13) {
          $("#query_form").submit();
        }
      });
    });
  </script>

  <%= stylesheet_link_tag '/plugin_assets/redmine_working_hours/stylesheets/working_hours' %>
<% end %>

<h2><%=l(:label_working_hours_statistics)%></h2>

<%= form_tag({ :action => 'statistics'},:method => :get, :id => 'query_form') do %>
  <div id="query_form_with_buttons" class="hide-when-print">
    <div id="query_form_content">
      <fieldset id="filters" class="collapsible">
        <legend onclick="toggleFieldset(this);"><%= l(:label_filter_plural) %></legend>
        <div>
          <%= l(:field_starting) %>: <%= text_field_tag 'filter[begindate]', @begindate_filter, :size => 10 %><%= calendar_for('filter_begindate') %>
          <%= l(:field_ending) %>: <%= text_field_tag 'filter[enddate]', @enddate_filter, :size => 10 %><%= calendar_for('filter_enddate') %>
        </div>
      </fieldset>
    </div>
    <p class="buttons">
      <%= link_to_function l(:button_apply), '$("#query_form").submit()', :class => 'icon icon-checked' %>
      <%= link_to l(:button_clear), {}, :class => 'icon icon-reload'  %>
    </p>
  </div>
<% end %>

<table class="list">
  <thead>
    <th><%= l(:field_total) %></th>
    <th><%= l(:field_target) %></th>
    <th><%= l(:label_diff) %></th>
  </thead>
  <tr>
    <td><%= "#{'%.1f' % @actual_hours}h" %></td>
    <td><%= "#{'%.1f' % @target_hours}h" %></td>
    <td><%= "#{'%.1f' % @diff_hours}h" %></td>
  </tr>
</table>